### ISSUE TITLE
Can not get config right

### ISSUE THREAD

**Issue by petrepa** [wlgrd/thingy52_homeassistant#2]
Hi, trying to follow the instructions, but can't quite get the config right. Found the mac to the thingy and put it into the config, but HA just outputs this when I check it.

`Testing configuration at /home/homeassistant/.homeassistant
2018-03-03 15:56:15 ERROR (Thread-2) [homeassistant.util.yaml] while parsing a block mapping
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 131, column 5
expected <block end>, but found '<block mapping start>'
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 140, column 7
2018-03-03 15:56:15 ERROR (MainThread) [homeassistant.bootstrap] Error loading /home/homeassistant/.homeassistant/configuration.yaml: while parsing a block mapping
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 131, column 5
expected <block end>, but found '<block mapping start>'
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 140, column 7`

Any idea how to fix this?

**Comment by wlgrd** [comment]
You need to paste your config, this is just guess work without knowing how the file looks like. It seems to be some indentation error.

**Comment by petrepa** [comment]
This is how the sensor part of the config looks like: 
```
sensor:
   # First thingy
  - platform: thingy52
 # Add your custom name here
    friendly_name: Bathroom
    scan_interval: 60
 # 1 = 1 s interval
 # 2 = 10 s interval
 # 3 = 60 s interval
    gas_interval: 3
    mac: "F9:3F:ED:75:64:43"
    sensors:
      temperature:
      humidity:
      co2:
      tvoc:
      pressure:
      battery:
```

Just copy/pasted from the instruction, and corrected it so it should have the right indentation (so far as I can see).
